language: r
cache: packages
latex: false
pandoc: false
fortran: false

matrix:
  include:
    - dist: precise
    - dist: xenial
    - os: osx
      brew_packages: webp
    - os: osx
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
    - libwebp-dev

notifications:
  email:
    on_success: change
    on_failure: change
